pipeline {
    agent {
        label 'NPM'
    }
    stages {
        stage('Build') {
            steps {
                sh "npm install"
            }
        }
        stage('Publish') {
            steps {
                sh "npm version 0.1.\$BUILDNUMBER"
            }
        }
    }
}